### PR TITLE
Update webkitgtk (didn't build)

### PR DESCRIPTION
**Pull request by maandree**
These patchsets for webkitgtk update:

• icu59.patch
since at least to releases on AUR, patch(1) rejected it because
of outdated context, and

• enchant-2.x.patch
was not a valid text file according to POSIX,[1] and those rejected
by implementions of patch(1) that do not do more than POSIX
ask of it.

[1] Did not end with a <new line> character and was therefore
a binary rather than a text file, and used CR LF instead of LF
where as the file it patched used LF so no lines matched since
LF is the only <new line> that need to be supported.

### CODE REVIEW

**Comment by yan12125** [comment]
Thanks! This patch looks good. I just need some time to test it :)

Out of curious, what's your patch(1) implementation? Maybe I can test against it before releasing problematic patches to AUR.

**Comment by maandree** [comment]
I use https://github.com/maandree/sbase/blob/patch/patch.c

**Comment by maandree** [comment]
Side-note: git diff may produce patchsets, even for text files, that are not supported by patch(1posix), in particular, this happens when adding, removing, or renaming files or changing their permissions or mode, my patch(1) may support that in future, so you may want to keep testing with the current version in the future too. You should also stick to using unified diffs as other implementations are a bit buggy when it comes to other formats (and in general).

**Comment by yan12125** [comment]
Thanks! Merged and pushed to AUR.

I'll sbase if I find time. Currently I don't know how to replace the default patch package in clean chroots.

**Comment by yan12125** [comment]
Oh, patch.c is still in your fork only and not upstreamed. Do you have a plan to submit it to suckless.org?

**Pull request merged**
